//
//  RadiusError.h
//  radius
//
//  Created by Radius on 11/9/12.
//
//

#import <Foundation/Foundation.h>

@interface RadiusError : NSObject

typedef enum {
    // Errors generated by backend
    RadiusErrorError = 0,
    RadiusErrorMissingParameters = 1,
    RadiusErrorIncorrectMethod = 2,
    RadiusErrorInvalidCredentials = 3,
    RadiusErrorBadToken = 4,
    RadiusErrorInvalidFormat = 5,
    RadiusErrorBeaconNotFound = 6,
    RadiusErrorUnsecuredRequest = 7,
    RadiusErrorUnauthorizedAction = 8,
    RadiusErrorBadAttachment = 9,
    RadiusErrorMethodUnimplemented = 10,
    RadiusErrorIoError = 11,
    RadiusErrorInvalidImage = 12,
    RadiusErrorFileTooLarge = 13,
    RadiusErrorPostNotFound = 14,
    RadiusErrorBadFbCredentials = 15,
    RadiusErrorNotFbConnected = 16,
    RadiusErrorFormError = 17,
    RadiusErrorBeaconPasswordIncorrect = 18,
    RadiusErrorBeaconPasswordRequired = 19,
    RadiusErrorBeaconAccessRestricted = 20,
    RadiusErrorBadTwitterCredentials = 21,
    RadiusErrorNotTwitterConnected = 22,
    RadiusErrorUserNotFound = 23,
    RadiusErrorIllegalAttachmentFiletype = 24,
    RadiusErrorParentNotFound = 25,
    RadiusErrorParentInDifferentBeacon = 26,
    RadiusErrorFbAlreadyConnected = 27,
    RadiusErrorInvalidFields = 28,
    RadiusErrorNotFound = 29,
    RadiusErrorTokenExpired = 30,
    RadiusErrorFbError = 31,
    RadiusErrorBadVideoLink = 32,
    RadiusErrorNoPasswordSet = 33,
    RadiusErrorStaleFbCredentials = 34,
    
    // Errors we detect in app
    RadiusErrorBadResponse = 1000,
    RadiusErrorUnknownError = 1001, // app received an unrecognized error code from the backend
} RadiusErrorType;


#define MAX_BACKEND_ERROR_CODE RadiusErrorStaleFbCredentials

@property (nonatomic) RadiusErrorType type;
@property (nonatomic,strong) NSString *message;

// Contains specific field errors for FormErrors
@property (nonatomic,strong) NSDictionary *errors;

-(id)initWithResponseObject:(NSDictionary *)responseObject;
-(id)initWithType:(RadiusErrorType)type message:(NSString *)message;

@end
